# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: docker pull testws/ws4dev:wss-remediate
  displayName: 'pull docker image'
- script: docker images
  displayName: 'list docker images'

#- task: WhiteSource@21
#  inputs:
#    cwd: '$(System.DefaultWorkingDirectory)'
#    projectName: 'GithubJsYarnSanity'
#    configuration: |
#      npm.yarnProject=true
#      npm.runPreStep=true