# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: eho Hi World
  displayName: 'Hi World'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    command: 'login'
- script: docker pull dockerdevws/wstestdata:C7954602
  displayName: 'docker pull'
- script: docker images
  displayName: 'docker images'

#- task: WhiteSource@21
#  inputs:
#    cwd: '$(System.DefaultWorkingDirectory)'
#    projectName: 'GithubJsYarnSanity'
#    configuration: |
#      npm.yarnProject=true
#      npm.runPreStep=true